#!/bin/bash

# Give the core subsystems a moment to stabilize
sleep 5

# Enable ZRAM
modprobe zram num_devices=1
TOTAL_RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
ZRAM_SIZE=$((TOTAL_RAM * 1024 / 2))
echo lz4 > /sys/block/zram0/comp_algorithm
echo $ZRAM_SIZE > /sys/block/zram0/disksize
mkswap /dev/zram0
swapon -p 100 /dev/zram0
sysctl -w vm.swappiness=100
