#!/bin/bash
# ZRam Manager for ROCKNIX Handheld Devices
# Operated via Gamepad TUI (dialog + gptokeyb)

# Ensure script is run as root
if [ "$(id -u)" -ne 0 ]; then
    exec sudo -- "$0" "$@"
fi

# Function to detect the active console TTY dynamically
GetActiveTTY() {
    if [ -f /sys/class/tty/tty0/active ]; then
        local active
        active=$(cat /sys/class/tty/tty0/active)
        if [ -n "$active" ]; then
            echo "/dev/$active"
            return 0
        fi
    fi
    if [ -c /dev/tty ]; then
        echo "/dev/tty"
        return 0
    fi
    echo "/dev/tty1"
    return 1
}

# Resolve active TTY
CURR_TTY=$(GetActiveTTY)

# Redirect standard outputs and inputs for the initialization
chmod 666 "$CURR_TTY" 2>/dev/null || true
chmod 666 /dev/uinput 2>/dev/null || true
printf "\e[?25l" > "$CURR_TTY" # Hide cursor
printf "\033c" > "$CURR_TTY"   # Clear screen

# Set up environment
export TERM=linux
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

# Ensure we are in the script's directory
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd "$SCRIPT_DIR"

BACKTITLE="ZRam Manager for ROCKNIX Handhelds"

# Verify dialog exists
if ! command -v dialog >/dev/null 2>&1; then
    printf "\nERROR: 'dialog' utility is not installed.\n" > "$CURR_TTY"
    exit 1
fi

# Helper to find gptokeyb on ROCKNIX
FindGptokeyb() {
    if [ -n "$GPTOKEYB" ] && [ -x "$GPTOKEYB" ]; then
        echo "$GPTOKEYB"
        return 0
    fi
    for p in "/usr/bin/gptokeyb" "/usr/local/bin/gptokeyb"; do
        if [ -x "$p" ]; then
            echo "$p"
            return 0
        fi
    done
    for p in "/storage/roms/ports/PortMaster/gptokeyb" \
             "/storage/roms/ports/PortMaster/gptokeyb.aarch64" \
             "/storage/roms/ports/gptokeyb" \
             "/storage/roms/ports/gptokeyb.aarch64"; do
        if [ -x "$p" ]; then
            echo "$p"
            return 0
        fi
    done
    local searched
    searched=$(find /storage/roms/ports/ -name "gptokeyb" -type f -executable -print -quit 2>/dev/null)
    if [ -n "$searched" ]; then
        echo "$searched"
        return 0
    fi
    searched=$(find /storage/roms/ports/ -name "gptokeyb.aarch64" -type f -executable -print -quit 2>/dev/null)
    if [ -n "$searched" ]; then
        echo "$searched"
        return 0
    fi
    echo ""
    return 1
}

# Clean exit handler
ExitMenu() {
    printf "\033c" > "$CURR_TTY"
    printf "\e[?25h" > "$CURR_TTY" # Show cursor
    if [ -n "$GPTOKEYB_PID" ]; then
        kill -9 "$GPTOKEYB_PID" 2>/dev/null || true
    fi
    pgrep -f gptokeyb | xargs kill -9 2>/dev/null || true
    exit 0
}

trap ExitMenu EXIT INT TERM

# Load / Save Config helpers
LoadConfig() {
    TOTAL_RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    CFG_SIZE=$((TOTAL_RAM / 1024 / 2)) # Default size (50% RAM)
    CFG_ALGO="lz4"
    CFG_AUTOSTART="true"
    
    if [ -f "/storage/.config/zram.conf" ]; then
        source "/storage/.config/zram.conf"
        [ -n "$ZRAM_SIZE_MB" ] && CFG_SIZE="$ZRAM_SIZE_MB"
        [ -n "$ZRAM_ALGO" ] && CFG_ALGO="$ZRAM_ALGO"
        [ -n "$ZRAM_AUTOSTART" ] && CFG_AUTOSTART="$ZRAM_AUTOSTART"
    fi
}

SaveConfig() {
    local size=$1
    local algo=$2
    local autostart=$3
    
    mkdir -p /storage/.config
    cat > "/storage/.config/zram.conf" << EOF
# ZRam Configuration for ROCKNIX
# Generated by ZRam Manager
ZRAM_SIZE_MB=${size}
ZRAM_ALGO=${algo}
ZRAM_AUTOSTART=${autostart}
EOF
    chmod 644 "/storage/.config/zram.conf"
}

WriteAutostartScript() {
    mkdir -p /storage/.config/autostart
    cat > "/storage/.config/autostart/010-zram-swap" << 'EOF'
#!/bin/bash

# Give the core subsystems a moment to stabilize
sleep 5

# Enable ZRAM
modprobe zram num_devices=1 2>/dev/null

# Wait up to 5 seconds for the block device to become available
for i in {1..10}; do
    [ -b /dev/zram0 ] && break
    sleep 0.5
done

if [ -b /dev/zram0 ]; then
    TOTAL_RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    ZRAM_SIZE=$((TOTAL_RAM * 1024 / 2))
    ZRAM_ALGO="lz4"

    # Load custom config if exists
    if [ -f "/storage/.config/zram.conf" ]; then
        source "/storage/.config/zram.conf"
        if [ "$ZRAM_AUTOSTART" = "false" ]; then
            exit 0
        fi
        if [ -n "$ZRAM_SIZE_MB" ]; then
            ZRAM_SIZE=$((ZRAM_SIZE_MB * 1024 * 1024))
        fi
    fi

    # Set compression algorithm
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        echo "$ZRAM_ALGO" > /sys/block/zram0/comp_algorithm 2>/dev/null
    fi

    # Initialize and enable ZRAM swap
    echo "$ZRAM_SIZE" > /sys/block/zram0/disksize
    mkswap /dev/zram0 >/dev/null 2>&1
    swapon -p 100 /dev/zram0
    sysctl -w vm.swappiness=100
fi
EOF
    chmod +x "/storage/.config/autostart/010-zram-swap"
}

RemoveAutostartScript() {
    rm -f "/storage/.config/autostart/010-zram-swap"
}

CheckZramStatus() {
    if [ -b /dev/zram0 ]; then
        if swapon -s | grep -q zram0; then
            local size_bytes
            size_bytes=$(cat /sys/block/zram0/disksize 2>/dev/null)
            local size_mb=$((size_bytes / 1024 / 1024))
            local algo
            algo=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -o '\[[^]]*\]' | tr -d '[]')
            [ -z "$algo" ] && algo="lz4"
            echo "ACTIVE|${size_mb}|${algo}"
            return 0
        fi
    fi
    echo "INACTIVE|0|none"
    return 1
}

ShowZramInfo() {
    # RAM stats
    local mem_total
    mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    local mem_free
    mem_free=$(awk '/MemFree/ {print $2}' /proc/meminfo)
    local mem_avail
    mem_avail=$(awk '/MemAvailable/ {print $2}' /proc/meminfo)
    
    local ram_total_mb=$((mem_total / 1024))
    local ram_free_mb=$((mem_free / 1024))
    local ram_avail_mb=$((mem_avail / 1024))
    local ram_used_mb=$((ram_total_mb - ram_avail_mb))
    
    # Swap stats
    local swap_total
    swap_total=$(awk '/SwapTotal/ {print $2}' /proc/meminfo)
    local swap_free
    swap_free=$(awk '/SwapFree/ {print $2}' /proc/meminfo)
    local swap_total_mb=$((swap_total / 1024))
    local swap_free_mb=$((swap_free / 1024))
    local swap_used_mb=$((swap_total_mb - swap_free_mb))
    
    # ZRAM details
    local zram_status
    zram_status=$(CheckZramStatus)
    IFS='|' read -r status size algo <<< "$zram_status"
    
    local stat_text=""
    if [ "$status" = "ACTIVE" ]; then
        local orig_mb=0
        local compr_mb=0
        local allocated_mb=0
        local ratio="N/A"
        
        if [ -f /sys/block/zram0/mm_stat ]; then
            read orig_bytes compr_bytes total_bytes limit max same pages_compacted huge <<< $(cat /sys/block/zram0/mm_stat)
            orig_mb=$((orig_bytes / 1024 / 1024))
            compr_mb=$((compr_bytes / 1024 / 1024))
            allocated_mb=$((total_bytes / 1024 / 1024))
            if [ "$compr_bytes" -gt 0 ] 2>/dev/null; then
                ratio=$(awk "BEGIN {printf \"%.2f:1\", $orig_bytes/$compr_bytes}")
            fi
        fi
        
        local autostart_status="Disabled"
        if [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ]; then
            autostart_status="Enabled"
        fi
        
        stat_text="=== ZRAM Swap Active ===
Status      : ACTIVE
Disk Size   : ${size} MB
Algorithm   : ${algo}
Autostart   : ${autostart_status}

=== Memory Stats ===
Total RAM   : ${ram_total_mb} MB
Used RAM    : ${ram_used_mb} MB
Available   : ${ram_avail_mb} MB

=== Swap Stats ===
Total Swap  : ${swap_total_mb} MB
Used Swap   : ${swap_used_mb} MB
Free Swap   : ${swap_free_mb} MB

=== ZRAM Metrics ===
Uncompressed: ${orig_mb} MB
Compressed  : ${compr_mb} MB
Memory Alloc: ${allocated_mb} MB
Compress Ratio: ${ratio}"
    else
        local autostart_status="Disabled"
        if [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ]; then
            autostart_status="Enabled (but not running)"
        fi
        
        stat_text="=== ZRAM Swap Inactive ===
Status      : INACTIVE
Autostart   : ${autostart_status}

=== Memory Stats ===
Total RAM   : ${ram_total_mb} MB
Used RAM    : ${ram_used_mb} MB
Available   : ${ram_avail_mb} MB

=== Swap Stats ===
Total Swap  : ${swap_total_mb} MB
Used Swap   : ${swap_used_mb} MB
Free Swap   : ${swap_free_mb} MB

Use 'Enable ZRAM' in the main menu to activate swap compression."
    fi
    
    dialog --backtitle "$BACKTITLE" \
           --title " ZRAM & Memory Stats " \
           --msgbox "$stat_text" 20 50 < "$CURR_TTY" 2> "$CURR_TTY"
}

EnableZram() {
    local size=$1
    local algo=$2
    
    DisableZram >/dev/null 2>&1
    sleep 0.5
    
    modprobe zram num_devices=1 2>/dev/null
    sleep 0.5
    
    if [ ! -b /dev/zram0 ]; then
        dialog --backtitle "$BACKTITLE" \
               --title " ERROR " \
               --msgbox "Failed to create /dev/zram0.\nEnsure ZRAM is supported in the kernel." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
        return 1
    fi
    
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        if grep -q "$algo" /sys/block/zram0/comp_algorithm; then
            echo "$algo" > /sys/block/zram0/comp_algorithm
        else
            dialog --backtitle "$BACKTITLE" \
                   --title " Warning " \
                   --msgbox "Algorithm '$algo' is not supported by your kernel.\nUsing default instead." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
        fi
    fi
    
    local size_bytes=$((size * 1024 * 1024))
    echo $size_bytes > /sys/block/zram0/disksize
    
    mkswap /dev/zram0 >/dev/null 2>&1
    swapon -p 100 /dev/zram0 2>/dev/null
    
    if [ $? -eq 0 ]; then
        sysctl -w vm.swappiness=100 >/dev/null 2>&1
        local actual_algo
        actual_algo=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -o '\[[^]]*\]' | tr -d '[]')
        [ -z "$actual_algo" ] && actual_algo="$algo"
        
        SaveConfig "$size" "$actual_algo" "true"
        WriteAutostartScript
        
        dialog --backtitle "$BACKTITLE" \
               --title " Success " \
               --msgbox "ZRAM successfully enabled and configured:\n\n- Size: ${size} MB\n- Algorithm: ${actual_algo}\n- Swappiness: 100\n- Autostart: Enabled" 12 45 < "$CURR_TTY" 2> "$CURR_TTY"
        return 0
    else
        dialog --backtitle "$BACKTITLE" \
               --title " ERROR " \
               --msgbox "Failed to enable ZRAM swap.\nCheck kernel log (dmesg)." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
        return 1
    fi
}

DisableZram() {
    if [ -b /dev/zram0 ]; then
        swapoff /dev/zram0 2>/dev/null
        echo 1 > /sys/block/zram0/reset 2>/dev/null
    fi
    rmmod zram 2>/dev/null
    
    LoadConfig
    SaveConfig "$CFG_SIZE" "$CFG_ALGO" "false"
    RemoveAutostartScript
}

SelectZramSize() {
    local mem_total
    mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    local ram_mb=$((mem_total / 1024))
    local rec_size=$((ram_mb / 2))
    [ $rec_size -lt 256 ] && rec_size=256
    [ $rec_size -gt 2048 ] && rec_size=2048
    
    local choices=()
    choices+=("$rec_size" "★ ${rec_size} MB (Recommended - 50% RAM)")
    
    for s in 256 512 1024 1536 2048; do
        if [ "$s" -ne "$rec_size" ] && [ "$s" -le "$ram_mb" ]; then
            choices+=("$s" "  ${s} MB")
        fi
    done
    
    local count=$((${#choices[@]} / 2))
    local menu_height=$((count + 7))
    
    local selection
    selection=$(dialog --backtitle "$BACKTITLE" \
                       --title " Select ZRAM Size " \
                       --default-item "$rec_size" \
                       --menu "Total System RAM: ${ram_mb} MB" \
                       $menu_height 50 $count \
                       "${choices[@]}" \
                       < "$CURR_TTY" 2> "$CURR_TTY")
    
    echo "$selection"
}

SelectZramAlgo() {
    if [ ! -b /dev/zram0 ]; then
        modprobe zram num_devices=1 2>/dev/null
        sleep 0.5
    fi
    
    local raw_algos="lz4 lzo zstd"
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        raw_algos=$(cat /sys/block/zram0/comp_algorithm | tr -d '[]')
    fi
    
    local choices=()
    local count=0
    for a in $raw_algos; do
        count=$((count + 1))
        if [ "$a" = "lz4" ]; then
            choices+=("$a" "★ lz4 (Recommended - Fastest)")
        elif [ "$a" = "zstd" ]; then
            choices+=("$a" "  zstd (High Compression)")
        else
            choices+=("$a" "  $a")
        fi
    done
    
    local menu_height=$((count + 7))
    local selection
    selection=$(dialog --backtitle "$BACKTITLE" \
                       --title " Select ZRAM Algorithm " \
                       --default-item "lz4" \
                       --menu "Available algorithms in kernel:" \
                       $menu_height 50 $count \
                       "${choices[@]}" \
                       < "$CURR_TTY" 2> "$CURR_TTY")
    
    echo "$selection"
}

ToggleAutostart() {
    LoadConfig
    if [ "$CFG_AUTOSTART" = "true" ]; then
        SaveConfig "$CFG_SIZE" "$CFG_ALGO" "false"
        RemoveAutostartScript
        dialog --backtitle "$BACKTITLE" \
               --title " Autostart Disabled " \
               --msgbox "Autostart has been disabled.\nZRAM will NOT start on boot." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
    else
        SaveConfig "$CFG_SIZE" "$CFG_ALGO" "true"
        WriteAutostartScript
        dialog --backtitle "$BACKTITLE" \
               --title " Autostart Enabled " \
               --msgbox "Autostart has been enabled.\nZRAM will start automatically on boot." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
    fi
}

MainMenu() {
    local mem_total
    mem_total=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    local ram_mb=$((mem_total / 1024))
    local rec_size=$((ram_mb / 2))
    [ $rec_size -lt 256 ] && rec_size=256
    
    while true; do
        local status_info
        status_info=$(CheckZramStatus)
        IFS='|' read -r status size algo <<< "$status_info"
        
        local status_display="Inactive"
        if [ "$status" = "ACTIVE" ]; then
            status_display="Active (${size}MB, ${algo})"
        fi
        
        local autostart_status="Disabled"
        if [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ]; then
            autostart_status="Enabled"
        fi
        
        local choice
        choice=$(dialog --backtitle "$BACKTITLE" \
                        --title " ZRAM Manager Main Menu " \
                        --ok-label "Select" \
                        --cancel-label "Exit" \
                        --menu "System RAM: ${ram_mb} MB\nZRAM Status: $status_display\nAutostart  : $autostart_status" \
                        16 55 6 \
                        1 "► View statistics & details" \
                        2 "► Enable ZRAM (Quick - ${rec_size}MB, lz4)" \
                        3 "► Enable ZRAM (Custom settings)" \
                        4 "► Disable ZRAM" \
                        5 "► Toggle Autostart (On/Off)" \
                        6 "► Exit" \
                        < "$CURR_TTY" 2> "$CURR_TTY")
        
        local ret=$?
        if [ $ret -ne 0 ]; then
            ExitMenu
        fi
        
        case "$choice" in
            1)
                ShowZramInfo
                ;;
            2)
                if [ "$status" = "ACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title " Information " \
                           --msgbox "ZRAM is already active.\nPlease disable ZRAM first to reconfigure." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
                else
                    EnableZram "$rec_size" "lz4"
                fi
                ;;
            3)
                if [ "$status" = "ACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title " Information " \
                           --msgbox "ZRAM is already active.\nPlease disable ZRAM first to reconfigure." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
                else
                    local selected_size
                    selected_size=$(SelectZramSize)
                    if [ -n "$selected_size" ]; then
                        local selected_algo
                        selected_algo=$(SelectZramAlgo)
                        if [ -n "$selected_algo" ]; then
                            EnableZram "$selected_size" "$selected_algo"
                        fi
                    fi
                fi
                ;;
            4)
                if [ "$status" = "INACTIVE" ]; then
                    dialog --backtitle "$BACKTITLE" \
                           --title " Information " \
                           --msgbox "ZRAM is not currently active." 7 40 < "$CURR_TTY" 2> "$CURR_TTY"
                else
                    dialog --backtitle "$BACKTITLE" \
                           --title " Confirm Disable " \
                           --yesno "Are you sure you want to disable ZRAM swap?\n\nThis will free up the ZRAM space instantly." 8 45 < "$CURR_TTY" 2> "$CURR_TTY"
                    if [ $? -eq 0 ]; then
                        DisableZram
                        dialog --backtitle "$BACKTITLE" \
                               --title " Disabled " \
                               --msgbox "ZRAM swap has been disabled and stopped." 7 40 < "$CURR_TTY" 2> "$CURR_TTY"
                    fi
                fi
                ;;
            5)
                ToggleAutostart
                ;;
            6)
                ExitMenu
                ;;
        esac
    done
}

# Find and launch gptokeyb
GPTOKEYB_BIN=$(FindGptokeyb)
GPTOKEYB_PID=""
if [ -n "$GPTOKEYB_BIN" ]; then
    pgrep -f gptokeyb | xargs kill -9 2>/dev/null || true
    "$GPTOKEYB_BIN" -1 "ZRam_Manager.sh" -c "./zram-manager.gptk" > /dev/null 2>&1 &
    GPTOKEYB_PID=$!
fi

# Run main interface
MainMenu
