#!/bin/bash
# ZRam Manager for ROCKNIX Handheld Devices
# Operated via Gamepad TUI (dialog + gptokeyb)
# Follows standard Portmaster launch script conventions

# ---- Wayland/Sway Terminal Nesting ----
# ROCKNIX runs under Wayland (Sway). Direct TTY console output is hidden/inactive.
# We must launch our script inside the 'foot' terminal emulator to render dialog on Sway.
if [ "$UI_SERVICE" = "sway.service essway.service" ] && [ "$1" != "--nested" ]; then
    exec foot -F "$0" --nested "$@"
fi

if [ "$1" = "--nested" ]; then
    shift
    IS_NESTED="true"
fi

# ---- Portmaster Environment Setup ----
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}

if [ -d "/opt/system/Tools/PortMaster/" ]; then
  controlfolder="/opt/system/Tools/PortMaster"
elif [ -d "/opt/tools/PortMaster/" ]; then
  controlfolder="/opt/tools/PortMaster"
elif [ -d "$XDG_DATA_HOME/PortMaster/" ]; then
  controlfolder="$XDG_DATA_HOME/PortMaster"
else
  controlfolder="/storage/roms/ports/PortMaster"
fi

if [ -f "$controlfolder/control.txt" ]; then
  source "$controlfolder/control.txt"
  [ -f "${controlfolder}/mod_${CFW_NAME}.txt" ] && source "${controlfolder}/mod_${CFW_NAME}.txt"
  get_controls
fi

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
cd "$SCRIPT_DIR"

# ---- TTY Detection (Only needed if NOT running nested inside foot terminal) ----
GetActiveTTY() {
    # Try the kernel's active VT first
    if [ -f /sys/class/tty/tty0/active ]; then
        local active
        active=$(cat /sys/class/tty/tty0/active 2>/dev/null)
        if [ -n "$active" ] && [ -c "/dev/$active" ] && [ -w "/dev/$active" ]; then
            echo "/dev/$active"
            return 0
        fi
    fi
    # Fallback to /dev/tty
    if [ -c /dev/tty ] && [ -w /dev/tty ]; then
        echo "/dev/tty"
        return 0
    fi
    # Last resort
    echo "/dev/tty0"
    return 0
}

if [ "$IS_NESTED" = "true" ]; then
    CURR_TTY=""
else
    CURR_TTY=$(GetActiveTTY)
    chmod 666 "$CURR_TTY" 2>/dev/null || true
    chmod 666 /dev/uinput 2>/dev/null || true
fi

export TERM=linux
export XDG_RUNTIME_DIR="/run/user/$(id -u)"

# ---- Dialog dimensions for handheld screens ----
height="15"
width="55"

BACKTITLE="ZRam Manager for ROCKNIX"
GPTOKEYB_PID=""

# ---- Clean Exit ----
ExitMenu() {
    # Disable traps immediately to prevent recursive calls
    trap - EXIT INT TERM
    
    if [ -n "$CURR_TTY" ]; then
        printf "\033c" > "$CURR_TTY" 2>/dev/null
        printf "\e[?25h" > "$CURR_TTY" 2>/dev/null
    fi
    
    # Kill only our gptokeyb instance
    if [ -n "$GPTOKEYB_PID" ]; then
        kill -9 "$GPTOKEYB_PID" 2>/dev/null
    fi
    
    if [ "$IS_NESTED" = "true" ]; then
        exit 0
    elif command -v pm_finish >/dev/null 2>&1; then
        pm_finish
    else
        exit 0
    fi
}

trap ExitMenu EXIT INT TERM

# ---- Verify dialog is available ----
if ! command -v dialog >/dev/null 2>&1; then
    if [ -n "$CURR_TTY" ]; then
        echo "ERROR: dialog not found" > "$CURR_TTY"
    else
        echo "ERROR: dialog not found"
    fi
    sleep 2
    exit 1
fi

# ---- Find gptokeyb ----
FindGptokeyb() {
    if [ -n "$GPTOKEYB2" ] && [ -x "$GPTOKEYB2" ]; then
        echo "$GPTOKEYB2"
        return 0
    fi
    if [ -n "$GPTOKEYB" ] && [ -x "$GPTOKEYB" ]; then
        echo "$GPTOKEYB"
        return 0
    fi
    if command -v gptokeyb >/dev/null 2>&1; then
        command -v gptokeyb
        return 0
    fi
    # Check common system paths
    local paths="/usr/bin/gptokeyb /usr/local/bin/gptokeyb"
    paths="$paths $controlfolder/gptokeyb $controlfolder/gptokeyb.aarch64"
    for p in $paths; do
        if [ -x "$p" ]; then
            echo "$p"
            return 0
        fi
    done
    return 1
}

# ---- Config Helpers ----
LoadConfig() {
    local total_ram_kb
    total_ram_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    CFG_SIZE=$((total_ram_kb / 1024 / 2))
    [ "$CFG_SIZE" -lt 256 ] && CFG_SIZE=256
    [ "$CFG_SIZE" -gt 2048 ] && CFG_SIZE=2048
    CFG_ALGO="lz4"
    CFG_AUTOSTART="true"
    if [ -f "/storage/.config/zram.conf" ]; then
        source "/storage/.config/zram.conf"
        [ -n "$ZRAM_SIZE_MB" ] && CFG_SIZE="$ZRAM_SIZE_MB"
        [ -n "$ZRAM_ALGO" ] && CFG_ALGO="$ZRAM_ALGO"
        [ -n "$ZRAM_AUTOSTART" ] && CFG_AUTOSTART="$ZRAM_AUTOSTART"
    fi
}

SaveConfig() {
    mkdir -p /storage/.config
    cat > "/storage/.config/zram.conf" << EOF
# ZRam Configuration for ROCKNIX
# Generated by ZRam Manager
ZRAM_SIZE_MB=$1
ZRAM_ALGO=$2
ZRAM_AUTOSTART=$3
EOF
    chmod 644 "/storage/.config/zram.conf"
}

WriteAutostartScript() {
    mkdir -p /storage/.config/autostart
    cat > "/storage/.config/autostart/010-zram-swap" << 'AUTOSTART_EOF'
#!/bin/bash
sleep 5
modprobe zram num_devices=1 2>/dev/null
for i in $(seq 1 10); do
    [ -b /dev/zram0 ] && break
    sleep 0.5
done
if [ -b /dev/zram0 ]; then
    TOTAL_RAM=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    ZRAM_SIZE=$((TOTAL_RAM * 1024 / 2))
    ZRAM_ALGO="lz4"
    if [ -f "/storage/.config/zram.conf" ]; then
        source "/storage/.config/zram.conf"
        [ "$ZRAM_AUTOSTART" = "false" ] && exit 0
        [ -n "$ZRAM_SIZE_MB" ] && ZRAM_SIZE=$((ZRAM_SIZE_MB * 1024 * 1024))
    fi
    [ -f /sys/block/zram0/comp_algorithm ] && echo "$ZRAM_ALGO" > /sys/block/zram0/comp_algorithm 2>/dev/null
    echo "$ZRAM_SIZE" > /sys/block/zram0/disksize
    mkswap /dev/zram0 >/dev/null 2>&1
    swapon -p 100 /dev/zram0
    sysctl -w vm.swappiness=100 >/dev/null 2>&1
fi
AUTOSTART_EOF
    chmod +x "/storage/.config/autostart/010-zram-swap"
}

RemoveAutostartScript() {
    rm -f "/storage/.config/autostart/010-zram-swap"
}

# ---- ZRAM Status ----
CheckZramStatus() {
    if [ -b /dev/zram0 ] && swapon -s 2>/dev/null | grep -q zram0; then
        local size_bytes algo
        size_bytes=$(cat /sys/block/zram0/disksize 2>/dev/null || echo 0)
        algo=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -o '\[[^]]*\]' | tr -d '[]')
        [ -z "$algo" ] && algo="unknown"
        echo "ACTIVE|$((size_bytes / 1024 / 1024))|${algo}"
        return 0
    fi
    echo "INACTIVE|0|none"
    return 1
}

# ---- Dialog Wrappers ----
# For dialogs that need to CAPTURE a user selection (menu)
run_menu() {
    local val
    if [ -n "$CURR_TTY" ]; then
        val=$(dialog --stdout "$@" 2>"$CURR_TTY" < "$CURR_TTY")
    else
        val=$(dialog --stdout "$@")
    fi
    local ret=$?
    echo "$val"
    sleep 0.2
    return $ret
}

# For dialogs that just DISPLAY info (msgbox, yesno)
run_dialog() {
    if [ -n "$CURR_TTY" ]; then
        dialog "$@" 2>"$CURR_TTY" < "$CURR_TTY"
    else
        dialog "$@"
    fi
    local ret=$?
    sleep 0.2
    return $ret
}

# ---- Show Stats ----
ShowZramInfo() {
    local mem_total mem_avail swap_total swap_free
    mem_total=$(($(awk '/MemTotal/ {print $2}' /proc/meminfo) / 1024))
    mem_avail=$(($(awk '/MemAvailable/ {print $2}' /proc/meminfo) / 1024))
    swap_total=$(($(awk '/SwapTotal/ {print $2}' /proc/meminfo) / 1024))
    swap_free=$(($(awk '/SwapFree/ {print $2}' /proc/meminfo) / 1024))
    local mem_used=$((mem_total - mem_avail))
    local swap_used=$((swap_total - swap_free))

    local zram_status
    zram_status=$(CheckZramStatus)
    IFS='|' read -r status zsize zalgo <<< "$zram_status"

    local text=""
    if [ "$status" = "ACTIVE" ]; then
        local ratio="N/A"
        if [ -f /sys/block/zram0/mm_stat ]; then
            local orig comp
            orig=$(awk '{print $1}' /sys/block/zram0/mm_stat 2>/dev/null)
            comp=$(awk '{print $2}' /sys/block/zram0/mm_stat 2>/dev/null)
            [ "$comp" -gt 0 ] 2>/dev/null && ratio=$(awk "BEGIN {printf \"%.1f:1\", $orig/$comp}")
        fi
        local auto_st="Off"
        [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ] && auto_st="On"
        text="ZRAM: ACTIVE  ${zsize}MB  ${zalgo}
Autostart: ${auto_st}  Ratio: ${ratio}

RAM: ${mem_used}/${mem_total} MB used
Swap: ${swap_used}/${swap_total} MB used"
    else
        local auto_st="Off"
        [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ] && auto_st="On"
        text="ZRAM: INACTIVE
Autostart: ${auto_st}

RAM: ${mem_used}/${mem_total} MB used
Swap: ${swap_used}/${swap_total} MB used"
    fi
    run_dialog --backtitle "$BACKTITLE" --title " Stats " --msgbox "$text" $height $width
}

# ---- Enable ZRAM ----
EnableZram() {
    local size_mb=$1 algo=$2

    # Tear down any existing zram first
    swapoff /dev/zram0 2>/dev/null
    [ -b /dev/zram0 ] && echo 1 > /sys/block/zram0/reset 2>/dev/null
    rmmod zram 2>/dev/null
    sleep 0.3

    modprobe zram num_devices=1 2>/dev/null
    sleep 0.3

    if [ ! -b /dev/zram0 ]; then
        run_dialog --backtitle "$BACKTITLE" --title " Error " --msgbox "Cannot create /dev/zram0.\nZRAM kernel module may be missing." $height $width
        return 1
    fi

    # Set algorithm
    if [ -f /sys/block/zram0/comp_algorithm ]; then
        if grep -q "$algo" /sys/block/zram0/comp_algorithm 2>/dev/null; then
            echo "$algo" > /sys/block/zram0/comp_algorithm 2>/dev/null
        fi
    fi

    echo $((size_mb * 1024 * 1024)) > /sys/block/zram0/disksize
    mkswap /dev/zram0 >/dev/null 2>&1
    swapon -p 100 /dev/zram0 2>/dev/null

    if [ $? -eq 0 ]; then
        sysctl -w vm.swappiness=100 >/dev/null 2>&1
        local actual_algo
        actual_algo=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -o '\[[^]]*\]' | tr -d '[]')
        [ -z "$actual_algo" ] && actual_algo="$algo"
        SaveConfig "$size_mb" "$actual_algo" "true"
        WriteAutostartScript
        run_dialog --backtitle "$BACKTITLE" --title " OK " --msgbox "ZRAM enabled: ${size_mb}MB ${actual_algo}\nAutostart: On" $height $width
    else
        run_dialog --backtitle "$BACKTITLE" --title " Error " --msgbox "Failed to enable ZRAM swap." $height $width
        return 1
    fi
}

# ---- Disable ZRAM ----
DisableZram() {
    swapoff /dev/zram0 2>/dev/null
    [ -b /dev/zram0 ] && echo 1 > /sys/block/zram0/reset 2>/dev/null
    rmmod zram 2>/dev/null
    LoadConfig
    SaveConfig "$CFG_SIZE" "$CFG_ALGO" "false"
    RemoveAutostartScript
}

# ---- Size Selection ----
SelectZramSize() {
    local total_ram_kb total_ram_mb rec
    total_ram_kb=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    total_ram_mb=$((total_ram_kb / 1024))
    rec=$((total_ram_mb / 2))
    [ "$rec" -lt 256 ] && rec=256
    [ "$rec" -gt 2048 ] && rec=2048

    local choices=("$rec" "Recommended (${rec}MB)")
    for s in 256 512 1024 1536 2048; do
        [ "$s" -ne "$rec" ] && [ "$s" -le "$total_ram_mb" ] && choices+=("$s" "${s} MB")
    done
    local cnt=$((${#choices[@]} / 2))

    run_menu --backtitle "$BACKTITLE" --title " ZRAM Size " --default-item "$rec" \
        --menu "RAM: ${total_ram_mb} MB" $height $width $cnt "${choices[@]}"
}

# ---- Algo Selection ----
SelectZramAlgo() {
    [ ! -b /dev/zram0 ] && { modprobe zram num_devices=1 2>/dev/null; sleep 0.3; }

    local raw="lz4 lzo zstd"
    [ -f /sys/block/zram0/comp_algorithm ] && raw=$(cat /sys/block/zram0/comp_algorithm | tr -d '[]')

    local choices=() cnt=0
    for a in $raw; do
        cnt=$((cnt + 1))
        case "$a" in
            lz4)  choices+=("$a" "lz4 - Fastest (recommended)") ;;
            zstd) choices+=("$a" "zstd - High compression") ;;
            *)    choices+=("$a" "$a") ;;
        esac
    done

    run_menu --backtitle "$BACKTITLE" --title " Algorithm " --default-item "lz4" \
        --menu "Select compression:" $height $width $cnt "${choices[@]}"
}

# ---- Toggle Autostart ----
ToggleAutostart() {
    LoadConfig
    if [ "$CFG_AUTOSTART" = "true" ]; then
        SaveConfig "$CFG_SIZE" "$CFG_ALGO" "false"
        RemoveAutostartScript
        run_dialog --backtitle "$BACKTITLE" --title " Autostart " --msgbox "Autostart disabled." $height $width
    else
        SaveConfig "$CFG_SIZE" "$CFG_ALGO" "true"
        WriteAutostartScript
        run_dialog --backtitle "$BACKTITLE" --title " Autostart " --msgbox "Autostart enabled." $height $width
    fi
}

# ---- Main Menu Loop ----
MainMenu() {
    LoadConfig
    local rec_size="$CFG_SIZE"

    while true; do
        local zinfo
        zinfo=$(CheckZramStatus)
        IFS='|' read -r st sz al <<< "$zinfo"

        local stxt="Inactive"
        [ "$st" = "ACTIVE" ] && stxt="Active ${sz}MB ${al}"
        local auto="Off"
        [ -f "/storage/.config/autostart/010-zram-swap" ] && [ -x "/storage/.config/autostart/010-zram-swap" ] && auto="On"

        local choice
        choice=$(run_menu --backtitle "$BACKTITLE" --title " ZRAM Manager " \
            --ok-label "Select" --cancel-label "Exit" \
            --menu "ZRAM: $stxt | Auto: $auto" $height $width 6 \
            1 "View Stats" \
            2 "Enable (Quick ${rec_size}MB lz4)" \
            3 "Enable (Custom)" \
            4 "Disable ZRAM" \
            5 "Toggle Autostart" \
            6 "Exit")

        case "$?" in
            1|255) ExitMenu ;; # Cancel or ESC
        esac

        case "$choice" in
            1) ShowZramInfo ;;
            2)
                if [ "$st" = "ACTIVE" ]; then
                    run_dialog --backtitle "$BACKTITLE" --title " Info " --msgbox "Already active. Disable first." $height $width
                else
                    EnableZram "$rec_size" "lz4"
                fi
                ;;
            3)
                if [ "$st" = "ACTIVE" ]; then
                    run_dialog --backtitle "$BACKTITLE" --title " Info " --msgbox "Already active. Disable first." $height $width
                else
                    local sel_size sel_algo
                    sel_size=$(SelectZramSize)
                    if [ -n "$sel_size" ]; then
                        sel_algo=$(SelectZramAlgo)
                        [ -n "$sel_algo" ] && EnableZram "$sel_size" "$sel_algo"
                    fi
                fi
                ;;
            4)
                if [ "$st" = "INACTIVE" ]; then
                    run_dialog --backtitle "$BACKTITLE" --title " Info " --msgbox "ZRAM is not active." $height $width
                else
                    run_dialog --backtitle "$BACKTITLE" --title " Confirm " --yesno "Disable ZRAM swap?" $height $width
                    if [ $? -eq 0 ]; then
                        DisableZram
                        run_dialog --backtitle "$BACKTITLE" --title " Done " --msgbox "ZRAM disabled." $height $width
                    fi
                fi
                ;;
            5) ToggleAutostart ;;
            6|"") ExitMenu ;;
        esac
    done
}

# ---- Initialize Screen (Only if running on direct TTY) ----
if [ -n "$CURR_TTY" ]; then
    printf "\033c" > "$CURR_TTY" 2>/dev/null
    printf "\e[?25l" > "$CURR_TTY" 2>/dev/null
fi

# ---- Launch gptokeyb ----
# We use the correct gptokeyb binary and run it WITHOUT double quotes.
# This ensures that standard Portmaster helper arguments (like -1 or LD_PRELOAD) are evaluated correctly.
export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"

GPTOKEYB_BIN=$(FindGptokeyb)
GPTOKEYB_PID=""
if [ -n "$GPTOKEYB_BIN" ]; then
    pgrep -f gptokeyb | xargs kill -9 2>/dev/null || true
    if [ "$IS_NESTED" = "true" ]; then
        $GPTOKEYB_BIN "foot" -c "$SCRIPT_DIR/zram-manager.gptk" > "$SCRIPT_DIR/gptokeyb.log" 2>&1 &
    else
        $GPTOKEYB_BIN "bash" -c "$SCRIPT_DIR/zram-manager.gptk" > "$SCRIPT_DIR/gptokeyb.log" 2>&1 &
    fi
    GPTOKEYB_PID=$!
    sleep 0.3
fi

# ---- Run ----
MainMenu
